### PR TITLE
Fixed issue with email template variable

### LINKED ISSUE #145: Pay by Check Admin Email Shows Admin Name Instead of Member Name
**Describe the bug**
In the Payment by Check – Pending (send to admin) email template, the !!name!! placeholder incorrectly outputs the site administrator’s name (the recipient of the email) instead of the member’s name who just signed up. This results in the admin receiving an email that appears as if they themselves are the new member.

**To Reproduce**
1. Install and activate Paid Memberships Pro and the Pay by Check Add On.
2. Configure a membership level and complete a checkout using the Pay by Check gateway.
3. Observe the Payment by Check – Pending (send to admin) email received by the admin.
4. Notice that the !!name!! placeholder shows the admin’s name, not the member’s.

**Screenshots**
If applicable, please attach a screenshot to make your issue clearer.

**Expected behavior**
The !!name!! placeholder should display the name of the member who submitted the checkout, not the admin receiving the email.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://www.paidmembershipspro.com/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress Version: 6.8.1  
PHP Version: 7.4.33  
Paid Memberships Pro: v3.5.1  
Paid Memberships Pro - Pay by Check Add On: v1.1.4  
Server: Apache/2.4.57 (Ubuntu)  
Site Language: en_US  
Timezone: America/Los_Angeles  
HTTPS Status: true  
Multisite: false  
Environment Type: production  
```
</details>

### PR DESCRIPTION
**Pull request by andrewlimaza**
### Changelog entry

* BUG FIX: Fixed an issue for !!name!! and !!display_name!! variables showing the admins name, and not the members name for admin emails. See lines 145-146,

* REFACTOR: Adjusted the `@since` docblocks as it was incorrectly versioned and applied minor WPCS (fix spacing issues)

### All Submissions:

* [x] Have you followed the [Contributing guidelines](https://github.com/strangerstudios/pmpro-pay-by-check/blob/dev/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/strangerstudios/pmpro-pay-by-check/pulls/) for the same update/change?

### Changes proposed in this Pull Request:

Resolves #145 .

### How to test the changes in this Pull Request:

1. Configure a membership level and complete a checkout using the Pay by Check gateway.
2. Observe the Payment by Check – Pending (send to admin) email received by the admin.
3. Notice that the !!name!! and !!display_name!! placeholder shows the admin’s name, not the member’s.
4. Retest the above steps after merging this PR to see that either variable now shows the member's name.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

File: classes/email-templates/class-pmpro-email-template-check-pending-admin.php [hunk 1]
```diff
@@ -142,29 +142,29 @@ public function get_email_template_variables() {
 
 		$email_template_variables = array(
 			'subject' => $this->get_default_subject(),
-			'name' => $this->get_recipient_name(),
-			'display_name' => $this->get_recipient_name(),
+			'name' => $user->display_name,
```
Comment (andrewlimaza) [inline classes/email-templates/class-pmpro-email-template-check-pending-admin.php:145]: Here is where the change actually fixes the issue.
